# ===============================================
# PROJECT INFORMATION
# ===============================================
name: gainz_clan
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+5

# ===============================================
# ENVIRONMENT CONFIGURATION
# ===============================================
environment:
  sdk: ^3.8.1

# ===============================================
# PRODUCTION DEPENDENCIES
# ===============================================
dependencies:
  # Core Flutter SDK
  flutter:
    sdk: flutter

  # UI Components & Icons
  cupertino_icons: ^1.0.8
  simple_ruler_picker: ^0.1.1
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0

  # State Management & Navigation
  get: ^4.7.2

  # Camera & Media
  camera: ^0.10.5+9
  audioplayers: ^6.4.0
  screenshot: ^3.0.0

  # ML & AI
  google_mlkit_pose_detection: ^0.13.0

  # Device Features
  vibration: ^3.1.3
  permission_handler: ^11.3.1

  # Sharing & Social
  share_plus: ^7.2.1
  app_links: ^6.4.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.7.0

  # Networking & Data
  http: ^1.5.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  socket_io_client: ^2.0.3+1

  # Utilities
  phone_numbers_parser: ^9.0.3
  intl: ^0.19.0
  timezone: ^0.10.0

  # Charts & Visualization
  fl_chart: ^0.69.0

  # Calendar Integration
  add_2_calendar: ^3.0.1
  lottie: ^3.3.1

  # firebase
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  timer_flutter: ^0.2.3-beta
  carousel_slider: ^5.1.1

# ===============================================
# DEVELOPMENT DEPENDENCIES
# ===============================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ===============================================
# FLUTTER CONFIGURATION
# ===============================================
flutter:
  uses-material-design: true

  # Asset Configuration
  assets:
    - assets/images/
    - assets/sounds/
    - assets/json/
    - assets/level/
    - assets/screenshots/
    - assets/screenshots/ios

  # Font Configuration
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/cinzel/Cinzel-Regular.ttf

    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/montserrat/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/MontserratAlternates-Black.ttf
          weight: 900
